"""
Course metadata for The Villages golf courses.
"""

COURSE_METADATA = {
    "Belle Glade": {
        "course_type": "Championship",
        "address": "434 Moyer Loop",
        "zip": "32163",
        "region": "Central",
        "aliases": [],
    },
    "Bonifay": {
        "course_type": "Championship",
        "address": "1033 Pinellas Place",
        "zip": "32163",
        "region": "Central",
        "aliases": [],
    },
    "Cane Garden": {
        "course_type": "Championship",
        "address": "1728 Bailey Trail",
        "zip": "32162",
        "region": "Central",
        "aliases": [],
    },
    "Evans Prairie": {
        "course_type": "Championship",
        "address": "1824 Evans Prairie Trail",
        "zip": "32163",
        "region": "Central",
        "aliases": [],
    },
    "Glenview Champions": {
        "course_type": "Championship",
        "address": "3190 Glenview Rd",
        "zip": "32162",
        "region": "North",
        "aliases": [],
    },
    "Hacienda Hills": {
        "course_type": "Championship",
        "address": "1195 Morse Blvd",
        "zip": "32159",
        "region": "North",
        "aliases": [],
    },
    "Havana": {
        "course_type": "Championship",
        "address": "2488 O'Dell Circle",
        "zip": "32162",
        "region": "North",
        "aliases": [],
    },
    "Lopez Legacy": {
        "course_type": "Championship",
        "address": "17145 Buena Vista Blvd",
        "zip": "32162",
        "region": "North",
        "aliases": [],
    },
    "Mallory Hill": {
        "course_type": "Championship",
        "address": "1675 O'Dell Circle",
        "zip": "32162",
        "region": "North",
        "aliases": [],
    },
    "Orange Blossom Hills": {
        "course_type": "Championship",
        "address": "1548 Water Tower Circle",
        "zip": "32159",
        "region": "North",
        "aliases": [],
    },
    "Palmer Legends": {
        "course_type": "Championship",
        "address": "1645 Palmer Way",
        "zip": "32162",
        "region": "North",
        "aliases": [],
    },
    "Shallow Creek": {
        "course_type": "Championship",
        "address": "8007 Landstone Blvd",
        "zip": "33585",
        "region": "South",
        "aliases": [],
    },
    "Southern Oaks": {
        "course_type": "Championship",
        "address": "766 Marilee Place, Suite 110",
        "zip": "32163",
        "region": "Central",
        "aliases": [],
    },
    "Tierra Del Sol": {
        "course_type": "Championship",
        "address": "806 San Marino Dr",
        "zip": "32159",
        "region": "North",
        "aliases": [],
    },
    "Woodlands": {
        "course_type": "Championship",
        "address": "1480 Craig Ct",
        "zip": "33585",
        "region": "South",
        "aliases": [],
    },
    "Amberwood": {
        "course_type": "Executive",
        "address": "7415 SE 172nd Legacy Ln",
        "zip": "32159",
        "region": "North",
        "aliases": [],
    },
    "Bacall": {
        "course_type": "Executive",
        "address": "2042 Canal St",
        "zip": "32162",
        "region": "North",
        "aliases": [],
    },
    "Belmont": {
        "course_type": "Executive",
        "address": "534 Belvedere Blvd",
        "zip": "32162",
        "region": "North",
        "aliases": [],
    },
    "Bogart": {
        "course_type": "Executive",
        "address": "2042 Canal St",
        "zip": "32162",
        "region": "North",
        "aliases": [],
    },
    "Bonita Pass": {
        "course_type": "Executive",
        "address": "2313 Buttonwood Run",
        "zip": "32162",
        "region": "Central",
        "aliases": [],
    },
    "Briarwood": {
        "course_type": "Executive",
        "address": "8501 SE 172nd Legacy Ln",
        "zip": "32159",
        "region": "North",
        "aliases": [],
    },
    "Bellaire": {
        "course_type": "Executive",
        "address": "7028 Beebe Ct",
        "zip": "33585",
        "region": "South",
        "aliases": [],
    },
    "Chula Vista": {
        "course_type": "Executive",
        "address": "1019 Rio Grand Ave",
        "zip": "32159",
        "region": "North",
        "aliases": [],
    },
    "Churchill Greens": {
        "course_type": "Executive",
        "address": "534 Belvedere Blvd",
        "zip": "32162",
        "region": "North",
        "aliases": [],
    },
    "De La Vista": {
        "course_type": "Executive",
        "address": "803 San Marino Blvd",
        "zip": "32159",
        "region": "North",
        "aliases": [],
    },
    "El Diablo": {
        "course_type": "Executive",
        "address": "2381 Enrique Dr",
        "zip": "32159",
        "region": "North",
        "aliases": [],
    },
    "El Santiago": {
        "course_type": "Executive",
        "address": "2381 Enrique Dr",
        "zip": "32159",
        "region": "North",
        "aliases": [],
    },
    "Escambia": {
        "course_type": "Executive",
        "address": "3020 Moyer Loop",
        "zip": "32163",
        "region": "Central",
        "aliases": [],
    },
    "Gray Fox": {
        "course_type": "Executive",
        "address": "5674 Hummingbird Lane",
        "zip": "32163",
        "region": "Central",
        "aliases": [],
    },
    "Hawkes Bay": {
        "course_type": "Executive",
        "address": "740 Buena Vista Blvd",
        "zip": "32159",
        "region": "North",
        "aliases": [],
    },
    "Heron": {
        "course_type": "Executive",
        "address": "1261 Sunset Point Blvd",
        "zip": "32162",
        "region": "Central",
        "aliases": [],
    },
    "Hill Top": {
        "course_type": "Executive",
        "address": "1432 Water Tower Circle",
        "zip": "32159",
        "region": "North",
        "aliases": [],
    },
    "Laurel Oak": {
        "course_type": "Executive",
        "address": "6345 McNeill Dr",
        "zip": "33585",
        "region": "South",
        "aliases": [],
    },
    "Live Oak": {
        "course_type": "Executive / Pitch & Putt",
        "address": "6345 McNeill Dr",
        "zip": "33585",
        "region": "South",
        "aliases": [],
    },
    "Loblolly": {
        "course_type": "Executive",
        "address": "2197 Fenney Way",
        "zip": "32163",
        "region": "South",
        "aliases": [],
    },
    "Longleaf": {
        "course_type": "Executive",
        "address": "2217 Fenney Way",
        "zip": "32163",
        "region": "South",
        "aliases": [],
    },
    "Lowlands": {
        "course_type": "Executive",
        "address": "5197 Marsh Bend Trail",
        "zip": "32163",
        "region": "Central",
        "aliases": [],
    },
    "Mangrove": {
        "course_type": "Executive",
        "address": "3198 Hendry Drive",
        "zip": "32163",
        "region": "Central",
        "aliases": [],
    },
    "Marsh View": {
        "course_type": "Executive / Pitch & Putt",
        "address": "5223 Marsh Bend Trail",
        "zip": "32163",
        "region": "Central",
        "aliases": [],
    },
    "Mickylee": {
        "course_type": "Executive / Pitch & Putt",
        "address": "6772 Meggison Road",
        "zip": "32163",
        "region": "South",
        "aliases": [],
    },
    "Mira Mesa": {
        "course_type": "Executive",
        "address": "998 Rio Grande Ave",
        "zip": "32159",
        "region": "North",
        "aliases": [],
    },
    "Oakleigh": {
        "course_type": "Executive",
        "address": "7415 SE 172nd Legacy Ln",
        "zip": "32159",
        "region": "North",
        "aliases": [],
    },
    "Okeechobee": {
        "course_type": "Executive",
        "address": "3020 Moyer Loop",
        "zip": "32163",
        "region": "Central",
        "aliases": [],
    },
    "Palmetto": {
        "course_type": "Executive",
        "address": "3106 Hendry Drive",
        "zip": "32163",
        "region": "Central",
        "aliases": [],
    },
    "Pelican": {
        "course_type": "Executive",
        "address": "1261 Sunset Point Blvd",
        "zip": "32162",
        "region": "Central",
        "aliases": [],
    },
    "Pimlico": {
        "course_type": "Executive",
        "address": "534 Belvedere Blvd",
        "zip": "32162",
        "region": "North",
        "aliases": [],
    },
    "Redfish Run": {
        "course_type": "Executive",
        "address": "2376 Nobelton Lane",
        "zip": "32162",
        "region": "Central",
        "aliases": [],
    },
    "Red Fox": {
        "course_type": "Executive",
        "address": "5674 Hummingbird Lane",
        "zip": "32163",
        "region": "Central",
        "aliases": [],
    },
    "Richmond": {
        "course_type": "Executive / Pitch & Putt",
        "address": "4468 Burgess Drive",
        "zip": "32163",
        "region": "Central",
        "aliases": [],
    },
    "Roosevelt": {
        "course_type": "Executive",
        "address": "2735 Canal St",
        "zip": "32162",
        "region": "Central",
        "aliases": [],
    },
    "Saddlebrook": {
        "course_type": "Executive",
        "address": "2980 Saddlebrook Ln",
        "zip": "32159",
        "region": "North",
        "aliases": [],
    },
    "Sandhill": {
        "course_type": "Executive",
        "address": "2580 Buena Vista Blvd",
        "zip": "32162",
        "region": "Central",
        "aliases": [],
    },
    "Sarasota": {
        "course_type": "Executive",
        "address": "2991 Morse Blvd",
        "zip": "32163",
        "region": "Central",
        "aliases": [],
    },
    "Silver Lake": {
        "course_type": "Executive",
        "address": "679 Rainbow Blvd",
        "zip": "32159",
        "region": "North",
        "aliases": [],
    },
    "Southern Star": {
        "course_type": "Executive",
        "address": "2514 St. Charles Pl",
        "zip": "32162",
        "region": "Central",
        "aliases": [],
    },
    "Sweetgum": {
        "course_type": "Executive",
        "address": "3198 Hendry Drive",
        "zip": "32163",
        "region": "Central",
        "aliases": [],
    },
    "Tarpon Boil": {
        "course_type": "Executive",
        "address": "2376 Nobelton Lane",
        "zip": "32162",
        "region": "Central",
        "aliases": [],
    },
    "Truman": {
        "course_type": "Executive",
        "address": "2735 Canal St",
        "zip": "32162",
        "region": "Central",
        "aliases": [],
    },
    "Turtle Mound": {
        "course_type": "Executive",
        "address": "2605 Turtle Mound Path",
        "zip": "32162",
        "region": "Central",
        "aliases": [],
    },
    "Volusia": {
        "course_type": "Executive",
        "address": "128 Moyer Loop",
        "zip": "32163",
        "region": "Central",
        "aliases": [],
    },
    "Walnut Grove": {
        "course_type": "Executive",
        "address": "8501 SE 172nd Legacy Ln",
        "zip": "32159",
        "region": "North",
        "aliases": [],
    },
    "Yankee Clipper": {
        "course_type": "Executive",
        "address": "2514 St. Charles Pl",
        "zip": "32162",
        "region": "Central",
        "aliases": [],
    },
}


def lookup_course_metadata(course_label):
    """Match a scraped course label to structured metadata."""
    label = (course_label or "").strip()
    if not label:
        return None, {}

    lower_label = label.lower()
    for canonical_name, meta in COURSE_METADATA.items():
        if canonical_name.lower() in lower_label:
            return canonical_name, meta
        for alias in meta.get("aliases", []):
            if alias.lower() in lower_label:
                return canonical_name, meta
    return None, {}
